info.app.name: app-test
info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'


# ===================================================
# SSL CONSIGURATION
# ===================================================
#
# CREATE DEV CERTIFICATE
# cd ${project-dir}/src/main/resources/certificates
# openssl req -x509 -newkey rsa:4096 -keyout dev-key.pem -out dev-cert.pem -days 3650 -subj '/CN=localhost'
# openssl pkcs12 -export -in dev-cert.pem -inkey dev-key.pem -out dev-keystore.p12 -name tomcat -caname root
#
# IMPORTANT: You may give "always trust" permissions to the certificate "certificates/dev-cert.pem" in your
# operating system specific Keychain Tool to be able to visit the website
#
# NOTE: Comment all HTTPS configuration to start in HTTP only
#
environments:
  development:
    server:
      port: 9443
      port-http: 9080
      servlet:
        context-path: /test
        session:
          persistent: true
          store-dir: app-test
      ssl:
        enabled: true
        key-store-type: PKCS12
        key-store: classpath:certificates/dev-keystore.p12
        key-store-password: password
        key-alias: tomcat

# CREATE PRODUCTION CERTIFICATE
# See: https://certbot.eff.org/en/instructions
#
#  production:
#    server:
#      port: 443
#      port-http: 80
#      servlet:
#        context-path: /
#      ssl:
#        enabled: true
#        key-store-type: PKCS12
#        key-store: /etc/letsencrypt/live/domain.com/keystore.p12
#        key-store-password: KeyStorePassword
#        key-alias: tomcat

---

# ===================================================
# LDAP CONFIGURATION
# ===================================================
grails:
  plugin:
    springsecurity:
      providerNames:
        - daoAuthenticationProvider
        - externalIdAuthenticationProvider
#        - ldapAuthProvider
        - rememberMeAuthenticationProvider

---
grails:
  codegen:
    defaultPackage: test.app
  profile: web
  views:
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        scriptlet: html

---
spring:
  threads:
    virtual:
      enabled: true
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 20MB

---
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false

# Create DB with:
# CREATE DATABASE database_name CHARACTER SET utf8 COLLATE utf8_general_ci;

# Create USER with:
# CREATE USER myuser@localhost IDENTIFIED BY 'MyPassword';
# GRANT ALL ON *.* TO myuser@localhost;
dataSource:
  pooled: true
  jmxExport: true
  driverClassName: com.mysql.cj.jdbc.Driver
  dialect: org.hibernate.dialect.MySQLDialect

  url: jdbc:mysql://localhost:3306/goowee?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  username: root
  password: root

environments:

  development:
    dataSource:
      dbCreate: update

  test:
    dataSource:
      dbCreate: update

  production:
    dataSource:
      dbCreate: update
